(() => {
  'use strict';
  const b=window.COVERED_CALL_BOOK,$=id=>document.getElementById(id);
  const money=x=>x===null||x===undefined?'—':Number(x).toLocaleString('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2});
  const price=x=>x===null||x===undefined?'—':Number(x).toLocaleString('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:4});
  const number=x=>x===null||x===undefined?'—':Number(x).toLocaleString('en-US',{maximumFractionDigits:4});
  const pct=x=>x===null||x===undefined?'—':(100*x).toFixed(2)+'%';
  const datefmt=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});
  const et=t=>datefmt.format(new Date(t));
  const wall=t=>{const p=Object.fromEntries(datefmt.formatToParts(new Date(t)).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day} ${p.hour}:${p.minute}`;};
  const layout={paper_bgcolor:'#fff',plot_bgcolor:'#fff',font:{family:'system-ui, sans-serif',color:'#142535',size:12},margin:{l:72,r:28,t:24,b:58},hovermode:'x unified',legend:{orientation:'h',x:0,y:1.12},xaxis:{title:{text:'Time · America/New_York'},gridcolor:'#edf2f6'},yaxis:{title:{text:'USD'},tickprefix:'$',gridcolor:'#e4ebf1'},hoverlabel:{bgcolor:'#fff'}};
  const conf={responsive:true,displaylogo:false,modeBarButtonsToRemove:['lasso2d','select2d'],toImageButtonOptions:{format:'png',scale:2}};
  if (!b) {
    ['nav-chart','funds-chart','scatter-chart'].forEach(id=>Plotly.newPlot(id,[],{...layout,xaxis:{visible:false},yaxis:{visible:false},annotations:[{text:'Awaiting actual LSEG backtest results',xref:'paper',yref:'paper',x:.5,y:.5,showarrow:false,font:{size:17,color:'#53667a'}}]},conf));
    ['download-blotter','download-ledger','week','benchmark','showcash'].forEach(id=>$(id).disabled=true);
    return;
  }
  if(b.schema!==2) {$('status').textContent='Unsupported result schema. Rebuild with the HW 1.2 engine.';return;}
  const s=b.summary,q=b.quality,fit=b.regression;
  $('period').textContent=`${b.config.start} — ${b.config.end}`;
  const material=b.status!=='ready'||!s.calls_sold||fit.r2===null||q.negative_excess_marks||q.request_failures;
  $('status').className='notice'+(material?'':' ready');
  $('status').textContent=`LSEG historical snapshot · ${s.calls_sold} calls written / ${s.weeks} scheduled weeks · ${s.skipped_weeks} skipped · `+(b.unresolved.length?'UNRESOLVED EXPIRY — incomplete account':!s.calls_sold?'NO EXECUTED CALLS — check data access':q.request_failures?`${q.request_failures} unresolved source requests — incomplete request coverage`:'cash and positions reconciled to every booked event')+(q.missing_option_marks?` · ${q.missing_option_marks} unknown NAV marks`:'');
  $('ending-nav').textContent=money(s.ending_nav);$('return').textContent=`${pct(s.return)} price-only return · initial ${money(s.initial_cash)}`;
  $('premium').textContent=money(s.premium_collected);$('outcomes').textContent=`${s.expirations} / ${s.assignments}`;
  $('outcomes-note').textContent=`Expired / assigned · ${s.skipped_weeks} weeks skipped`;$('drawdown').textContent=pct(s.max_drawdown);
  const fact=(label,value)=>{const span=document.createElement('span');span.textContent=label+' ';const strong=document.createElement('b');strong.textContent=value;span.append(strong);return span;};
  $('account-facts').append(fact('Ending cash',money(s.ending_cash)),fact('Ending shares',number(s.ending_shares)),fact('Negative available marks',String(q.negative_available_marks)),fact('Maintenance breaches',String(q.negative_excess_marks)));
  const line=(name,key,color,dash='solid')=>({type:'scatter',mode:'lines',name,x:b.ledger.map(r=>wall(r.time)),y:b.ledger.map(r=>r[key]),connectgaps:false,line:{color,width:key==='nav'?3:1.7,dash},customdata:b.ledger.map(r=>[r.phase,r.mark_status]),hovertemplate:name+': $%{y:,.2f}<br>%{customdata[0]}<extra></extra>'});
  function drawNav(){const traces=[line('NAV','nav','#007d7a'),line('Initial margin','initial','#b55322','dash'),line('Maintenance','maintenance','#7750b1','dot')];if($('benchmark').checked)traces.push(line('100-share benchmark','benchmark_nav','#7991a5','dot'));if($('showcash').checked)traces.push(line('Cash','cash','#365ba5'));Plotly.react('nav-chart',traces,{...layout,uirevision:'nav'},conf);}
  drawNav();$('benchmark').addEventListener('change',drawNav);$('showcash').addEventListener('change',drawNav);
  Plotly.newPlot('funds-chart',[line('Available funds','available','#365ba5'),line('Excess equity','excess','#007d7a')],{...layout,margin:{l:72,r:28,t:30,b:50},shapes:[{type:'line',xref:'paper',x0:0,x1:1,y0:0,y1:0,line:{color:'#ae4940',width:1.5,dash:'dash'}}]},conf);
  const all=b.scatter,step=Math.max(1,Math.ceil(all.length/3000)),points=all.filter((_,i)=>i%step===0);
  $('r2').textContent=fit.r2===null?'N/A':fit.r2.toFixed(4);
  $('fit-equation').textContent=fit.slope===null?'Too few or degenerate matched observations: a fitted line and R² cannot be established.':`OLS: trade = ${fit.intercept.toFixed(4)} + ${fit.slope.toFixed(4)} × mid.`;
  $('fit-details').textContent=`${fit.n.toLocaleString()} exact contract/bar pairs; mean |trade − mid| = ${money(fit.mae)}. Each eligible call is within 10% of the same-bar stock price. Zero-volume trade bars are excluded when volume is reported.${step>1?` Plot displays ${points.length.toLocaleString()} evenly sampled points; the fit uses all pairs.`:''}`;
  const max=all.reduce((m,p)=>Math.max(m,p.mid,p.trade),1)*1.05;
  const traces=[{type:'scattergl',mode:'markers',name:'Observed bar pairs',x:points.map(p=>p.mid),y:points.map(p=>p.trade),customdata:points.map(p=>[p.ric,et(p.time)]),marker:{size:5,color:'#007d7a',opacity:.48},hovertemplate:'%{customdata[0]}<br>%{customdata[1]} ET<br>Mid: $%{x:.4f}<br>Trade: $%{y:.4f}<extra></extra>'},{type:'scatter',mode:'lines',name:'Trade = mid',x:[0,max],y:[0,max],line:{color:'#9eabb7',dash:'dot',width:1.5},hoverinfo:'skip'}];
  if(fit.slope!==null)traces.push({type:'scatter',mode:'lines',name:'OLS fit',x:[0,max],y:[fit.intercept,fit.intercept+fit.slope*max],line:{color:'#b55322',width:2},hoverinfo:'skip'});
  Plotly.newPlot('scatter-chart',traces,{...layout,hovermode:'closest',xaxis:{title:{text:'Mid = (BID + ASK) / 2 · USD'},range:[0,max],gridcolor:'#e4ebf1'},yaxis:{title:{text:'TRDPRC_1 · USD'},range:[0,max],gridcolor:'#e4ebf1'}},conf);
  $('sensitivity').textContent=`Same-path sensitivity: selling at the observed bid instead of mid would collect ${money(s.bid_fill_cost_same_path)} less; $0.65 commission per written call would cost ${money(s.commission_cost_at_065)}. These are cash-impact diagnostics, not a re-run with changed funding eligibility.`;
  $('analysis-result').textContent=`From ${money(s.initial_cash)}, the account ended at ${money(s.ending_nav)} (${pct(s.return)}), with ${money(s.ending_cash)} cash and ${s.ending_shares} shares. ${s.calls_sold} calls generated ${money(s.premium_collected)} in gross premium; ${s.expirations} expired and ${s.assignments} were assigned.`;
  const stockPnl=b.blotter.filter(r=>r.instrument===b.config.stock_ric).reduce((a,r)=>a+r.cash_delta,0);
  if(s.ending_shares===0)$('analysis-result').textContent+=` Cash attribution: ${money(stockPnl)} from stock purchases/deliveries + ${money(s.premium_collected)} option premium = ${money(s.ending_nav-s.initial_cash)} net P&L. Receiving premium did not remove the stock downside.`;
  $('analysis-path').textContent=`Observed maximum drawdown was ${pct(s.max_drawdown)}. The same-initial-cash 100-share price-only benchmark ended at ${money(s.benchmark_ending_nav)}${s.ending_nav!==null&&s.benchmark_ending_nav!==null?`, a strategy difference of ${money(s.ending_nav-s.benchmark_ending_nav)}`:''}. ${q.missing_option_marks?'NAV gaps make drawdown a measure of the observed marks only.':'Every recorded holding-period NAV has a usable mark.'}`;
  const expiryMarks=b.ledger.filter(r=>r.phase==='pre-expiry');
  const capExample=[...expiryMarks].sort((a,z)=>z.option_mark-a.option_mark)[0];
  if(capExample){const entry=b.blotter.find(r=>r.instrument===capExample.option_ric&&r.side==='SELL');const foregone=100*capExample.option_mark;const premium=entry?100*entry.fill:0;$('analysis-event').textContent=foregone>0?`A concrete expiry: on ${et(capExample.time)} ET, stock was ${money(capExample.stock_mark)} versus a ${money(capExample.strike)} strike. Assignment capped the stock proceeds at the strike, surrendering ${money(foregone)} of that day's upside above it. This call had collected ${money(premium)}; its premium minus expiry intrinsic was ${money(premium-foregone)} relative to retaining those same shares without this call. This is a single-call comparison, not total strategy P&L.`:`None of the settled calls finished ITM. For example, on ${et(capExample.time)} ET, spot ${money(capExample.stock_mark)} was at or below strike ${money(capExample.strike)}. The call expired, retaining the shares and its ${money(premium)} premium; subsequent stock downside remained in the account.`;}
  $('analysis-tape').textContent=`${s.skipped_weeks} of ${s.weeks} scheduled weeks were skipped; the decision audit gives the reason for each. ${q.request_failures} source requests remain unresolved, ${q.missing_option_marks} ledger rows lack an option midpoint, and ${q.negative_excess_marks} marked observations breach maintenance. ${q.negative_available_marks?'Negative available-funds observations indicate insufficient initial-margin room at those marks; they must not be described as a fully unconstrained account.':'No marked observation shows negative initial-margin room.'}`;
  const cashMin=Math.min(...b.ledger.map(r=>r.cash)),av=b.ledger.map(r=>r.available).filter(x=>x!==null);
  $('borrowing-note').textContent=`Lowest recorded cash balance: ${money(cashMin)}. ${cashMin<0?'Negative cash represents a margin debit financing part of the 100-share position. It is not itself a failed Reg T test; equity must cover the prescribed initial and maintenance requirements. Financing interest is excluded, so this price-only result is optimistic relative to a funded account.':'No margin debit appears in the recorded ledger.'} Minimum observed available funds: ${money(av.length?Math.min(...av):null)}.`;
  const weeks=[...new Set(b.decisions.map(r=>r.expiry))].sort();weeks.forEach(w=>{const o=document.createElement('option');o.value=w;o.textContent=w;$('week').append(o);});
  function td(tr,value,negative=false){const cell=document.createElement('td');cell.textContent=value;if(negative)cell.className='negative';tr.append(cell);return cell;}
  function weekFor(time){const d=new Date(time),p=Object.fromEntries(datefmt.formatToParts(d).map(x=>[x.type,x.value]));const day=new Date(`${p.year}-${p.month}-${p.day}T00:00:00Z`);day.setUTCDate(day.getUTCDate()+5-day.getUTCDay());return day.toISOString().slice(0,10);}
  function filtered(name){return b[name].filter(r=>$('week').value==='all'||(r.group||weekFor(r.time))===$('week').value);}
  function tables(){const events=filtered('blotter'),ledger=filtered('ledger');$('blotter').replaceChildren();$('ledger').replaceChildren();events.forEach(r=>{const tr=document.createElement('tr');td(tr,et(r.time));td(tr,r.instrument);const cell=td(tr,'');const badge=document.createElement('span');badge.textContent=r.side;badge.className='side '+r.side;cell.append(badge);td(tr,r.qty);td(tr,price(r.limit));td(tr,price(r.fill));td(tr,money(r.cash_delta),r.cash_delta<0);td(tr,money(r.cash_after),r.cash_after<0);td(tr,r.note);$('blotter').append(tr);});ledger.forEach(r=>{const tr=document.createElement('tr');[et(r.time),r.phase,money(r.cash),r.shares,r.option_ric?`${r.short_calls} short × ${r.option_ric} / ${r.expiry}`:'—',price(r.strike),price(r.stock_mark),price(r.option_mark),money(r.lmv),money(r.option_mv),money(r.nav),money(r.initial),money(r.maintenance),money(r.available),money(r.excess)].forEach((v,i)=>td(tr,v,([2,9,10,13,14].includes(i)&&String(v).startsWith('-'))));$('ledger').append(tr);});$('blotter-count').textContent=`${events.length} booked events shown. Week filter applies to blotter and ledger; charts and headline metrics always show the full backtest.`;$('ledger-count').textContent=`${ledger.length} marked account rows shown. Unknown values appear as —.`;}
  tables();$('week').addEventListener('change',tables);
  b.decisions.forEach(r=>{const failed=b.request_audit.filter(a=>a.status==='error'&&a.ric.startsWith(b.config.root+String.fromCharCode(65+Number(r.expiry.slice(5,7))-1)+Number(r.expiry.slice(8,10))+r.expiry.slice(2,4)));const reason=r.reason+(failed.length?` ${failed.length} candidate requests failed; this is unavailable source data, not proof that the options lacked a market.`:'');const tr=document.createElement('tr');[et(r.time),r.expiry,r.status,r.ric||'—',reason].forEach(v=>td(tr,v));$('decisions').append(tr);});
  b.request_audit.forEach(r=>{const tr=document.createElement('tr');[r.ric,r.status,r.rows,r.error||'—'].forEach(v=>td(tr,v));$('requests').append(tr);});
  $('provenance').textContent=`Source: ${b.provenance.provider||'unspecified'} · Retrieved: ${b.provenance.retrieved_at||'unknown'} · Completed: ${b.provenance.completed_at||'unknown'} · Checkpoint SHA-256: ${b.provenance.cache_sha256||'not supplied'}`;
  $('quality').textContent=`API: ${b.provenance.api||'unspecified'} · ${b.request_audit.length} candidate request records · ${q.zero_volume_pairs_excluded} zero-volume trade pairs excluded · ${b.unresolved.length} unresolved settlements. Any unresolved item limits the reported result.`;
  function download(name){const rows=filtered(name);if(!rows.length)return;const keys=Object.keys(rows[0]);const escape=x=>'"'+String(x??'').replaceAll('"','""')+'"';const csv=[keys.join(','),...rows.map(r=>keys.map(k=>escape(r[k])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`hw12-${name}-${$('week').value}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  $('download-blotter').addEventListener('click',()=>download('blotter'));$('download-ledger').addEventListener('click',()=>download('ledger'));
})();
